version: "3.8"
services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - 8000:8000
    command: -jar DynamoDBLocal.jar -dbPath /data -sharedDb
    volumes:
      - $PWD/dynamodb/data:/data
  dynamodb-admin:
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=dynamodb:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb
  lambda-cron:
    build:
      context: ./lambda/cron
      target: production
    container_name: lambda-cron
    ports:
      - 8080:8080
    environment:
      - tableName=${tableName}
      - dynamoDbEndpoint=${dynamoDbEndpoint}
      - env=${env}
      - userId=${userId}
  lambda-webhook:
    build:
      context: ./lambda/webhook
      target: production
    container_name: lambda-webhook
    ports:
      - 8081:8080
    environment:
      - tableName=${tableName}
      - dynamoDbEndpoint=${dynamoDbEndpoint}
      - env=${env}
      - userId=${userId}
